# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    brochures_directory: '%kernel.root_dir%/../web/uploads/user/profilpics'

services:
    app.profil_uploader:
        class: UserBundle\serviceController\fileUploader
        arguments: ['%brochures_directory%']
