<?php

namespace UserBundle\Repository;

/**
 * profilPicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class profilPicRepository extends \Doctrine\ORM\EntityRepository
{
}
