<?php

namespace UserBundle\Repository;

/**
 * raceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class raceRepository extends \Doctrine\ORM\EntityRepository
{
}
